### ISSUE TITLE
感谢分享, 正式运行报错  查到票后抢票时  

### ISSUE THREAD

**Issue by dq7532183** [pjialin/py12306#1]
Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\urllib3\connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

**Comment by pjialin** [comment]
看着像是网络错误，麻烦提供下上下文日志呢

**Comment by dq7532183** [comment]
[ 查询到座位可用 出发时间 20190204 车次 D2003 座位类型 二等座 余票数量 5 ]
检查完成 开始提交订单 
=== 正在进行第 684 次查询 === 2019-01-08 17:32:31.642242		
出发日期 2019-02-03: 北京 - 介休		G627-N		G605-N		D2003-N		安全停留 0.69		
出发日期 2019-02-04: 北京 - 介休		G627-N		G605-N		D2003-N		安全停留 0.89		

[ 查询到座位可用 出发时间 20190204 车次 D2003 座位类型 二等座 余票数量 5 ]
检查完成 开始提交订单 
=== 正在进行第 686 次查询 === 2019-01-08 17:32:34.095958		
出发日期 2019-02-03: 北京 - 介休		G627-N		G605-N		D2003-N		安全停留 0.55		

Exception in thread Thread-690:
Traceback (most recent call last):
  File "C:\Python3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\python\py12306\py12306\query\job.py", line 65, in run
    self.start()
  File "D:\python\py12306\py12306\query\job.py", line 80, in start
    self.handle_response(response)
  File "D:\python\py12306\py12306\query\job.py", line 126, in handle_response
    self.handle_seats(allow_seats, ticket_info)
  File "D:\python\py12306\py12306\query\job.py", line 152, in handle_seats
    order.order()
  File "D:\python\py12306\py12306\order\order.py", line 55, in order
    self.normal_order()
  File "D:\python\py12306\py12306\order\order.py", line 59, in normal_order
    if not self.submit_order_request(): return
  File "D:\python\py12306\py12306\order\order.py", line 103, in submit_order_request
    result = response.json()
  File "C:\Python3\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dq7532183** [comment]
程序没有影响,还在运行,就是cmd输出了提醒,没什么问题,感谢

**Comment by pjialin** [comment]
嗯，那个是返回的请求有误，上个版本已经加处理了，拉下代码就好了

**Comment by pjialin** [comment]
先关了，有问题再重新打开
