### ISSUE TITLE
感谢分享，但是运行的时候会报错

### ISSUE THREAD

**Issue by harryzheng93** [pjialin/py12306#13]
配置好文件之后运行时会显示
`Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main()
  File "main.py", line 13, in main
    CommonLog.print_welcome()
  File "C:\Users\LabMem No.318\py12306\py12306\log\common_log.py", line 54, in print_welcome
    if Config().WEB_ENABLE:
  File "C:\Users\LabMem No.318\py12306\py12306\helpers\func.py", line 29, in singleton_new
    it.__init_original__(*args, **kw)
  File "C:\Users\LabMem No.318\py12306\py12306\config.py", line 84, in __init__
    self.init_envs()
  File "C:\Users\LabMem No.318\py12306\py12306\config.py", line 123, in init_envs
    self.envs = EnvLoader.load_with_file(self.CONFIG_FILE)
  File "C:\Users\LabMem No.318\py12306\py12306\config.py", line 199, in load_with_file
    exec(content)
  File "<string>", line 97
    'members': [
             ^
SyntaxError: invalid syntax`
求教这是什么情况？

**Comment by harryzheng93** [comment]
好吧我傻了，前面不小心删掉一个符号
