### ISSUE TITLE
阿里云服务器上运行报错

### ISSUE THREAD

**Issue by Lollipop43** [pjialin/py12306#136]
配置之后在本地windows上运行正常
复制到Linux服务器上运行报错如下：
```[root@Torcy py12306-master]# python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from py12306.app import *
  File "/home/vsftp/Files/py12306-master/py12306/app.py", line 8, in <module>
    from py12306.helpers.notification import Notification
  File "/home/vsftp/Files/py12306-master/py12306/helpers/notification.py", line 5, in <module>
    from py12306.helpers.request import Request
  File "/home/vsftp/Files/py12306-master/py12306/helpers/request.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[root@Torcy py12306-master]#
```
python版本均为3.x

**Comment by kbj** [comment]
在py12306-master目录下执行
```
pip3 install -r requirements.txt
```

**Comment by pjialin** [comment]
#28
