### ISSUE TITLE
测试不通过

### ISSUE THREAD

**Issue by HuangDayu** [pjialin/py12306#14]
# 一
```shell
[root@izwz951e3fbtauq6d7ez9gz py12306]# python main.py -t -c ./env.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from py12306.app import *
  File "/root/py12306/py12306/app.py", line 29
SyntaxError: Non-ASCII character '\xe7' in file /root/py12306/py12306/app.py on line 30, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```
app.py & func.py & 

解决：
`# -*- coding: utf-8 -*-`

# 二
```shell
[root@izwz951e3fbtauq6d7ez9gz py12306]# python main.py -t -c ./env.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from py12306.app import *
  File "/root/py12306/py12306/app.py", line 6, in <module>
    from py12306.helpers.func import *
  File "/root/py12306/py12306/helpers/func.py", line 145
    def dict_count_key_num(data: dict, key, like=False):
                               ^
SyntaxError: invalid syntax
```

```shell
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from py12306.app import *
  File "/root/py12306/py12306/app.py", line 6, in <module>
    from py12306.helpers.func import *
  File "/root/py12306/py12306/helpers/func.py", line 186, in <module>
    @singleton
  File "/root/py12306/py12306/helpers/func.py", line 21, in singleton
    cls.__new_original__ = cls.__new__
AttributeError: class Const has no attribute '__new__'
```

未解决，请指教。

**Comment by slccper** [comment]
要使用 Python 3.6

**Comment by HuangDayu** [comment]
> 要使用 Python 3.6

好的，谢谢。
是抢到票后到12306客户端付款吗？

**Comment by LiangSlr** [comment]
`Traceback (most recent call last):
  File "C:/Users/sunshine/AppData/Local/Programs/Python/Python37/Lib/py12306/main.py", line 61, in <module>
    main()
  File "C:/Users/sunshine/AppData/Local/Programs/Python/Python37/Lib/py12306/main.py", line 13, in main
    CommonLog.print_welcome()
  File "C:\Users\sunshine\AppData\Local\Programs\Python\Python37\Lib\py12306\py12306\log\common_log.py", line 51, in print_welcome
    if not Const.IS_TEST and Config().OUT_PUT_LOG_TO_FILE_ENABLED:
  File "C:\Users\sunshine\AppData\Local\Programs\Python\Python37\Lib\py12306\py12306\helpers\func.py", line 29, in singleton_new
    it.__init_original__(*args, **kw)
  File "C:\Users\sunshine\AppData\Local\Programs\Python\Python37\Lib\py12306\py12306\config.py", line 86, in __init__
    self.init_envs()
  File "C:\Users\sunshine\AppData\Local\Programs\Python\Python37\Lib\py12306\py12306\config.py", line 125, in init_envs
    self.envs = EnvLoader.load_with_file(self.CONFIG_FILE)
  File "C:\Users\sunshine\AppData\Local\Programs\Python\Python37\Lib\py12306\py12306\config.py", line 202, in load_with_file
    exec(content)
  File "<string>", line 1
    ﻿# encoding=utf8
    ^
SyntaxError: invalid character in identifier`


运行出错，求指点问题

**Comment by LiangSlr** [comment]
line 125, in init_envs
    self.envs = EnvLoader.load_with_file(self.CONFIG_FILE)
  File "C:\Users\sunshine\AppData\Local\Programs\Python\Python37\Lib\py12306\py12306\config.py", line 202, in load_with_file
    exec(content)
  File "<string>", line 1
    ﻿# encoding=utf8
    ^
SyntaxError: invalid character in identifier`

运行出错，太长了我把前面的删除掉了，问题是exec函数执行时报错，报错内容 invalid character in identifier，求指点
