### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by op69qs** [pjialin/py12306#142]
```
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 20, in main
    Query.check_before_run()
  File "/home/ubuntu/git/py12306/py12306/query/query.py", line 59, in check_before_run
    self = cls()
  File "/home/ubuntu/git/py12306/py12306/helpers/func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "/home/ubuntu/git/py12306/py12306/query/query.py", line 35, in __init__
    self.get_query_api_type()
  File "/home/ubuntu/git/py12306/py12306/query/query.py", line 154, in get_query_api_type
    self.api_type = res.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by pjialin** [comment]
已修复
