### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by adaaaaaa** [pjialin/py12306#15]
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/captain/py12306/py12306/web/web.py", line 57, in run_session
    self.session.run(debug=debug, port=Config().WEB_PORT, host='0.0.0.0')
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3.7/site-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/usr/lib/python3.7/site-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/usr/lib/python3.7/site-packages/werkzeug/serving.py", line 660, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/lib/python3.7/site-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/usr/lib/python3.7/socketserver.py", line 449, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 463, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

报错了，看看怎么回事？

**Comment by pjialin** [comment]
检查下是否重复启动了？或是商品被占用了

**Comment by adaaaaaa** [comment]
@pjialin 并没有呢。。。我关掉spyder再打开，再运行又可以了。。。spyder有毒？😂😂😂

**Comment by pjialin** [comment]
@adaaaaaa  哈，一般是端口被占用了，再出现可以通过 `sudo lsof -i:8008` 查看下
先关了，有问题再打开
