### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by lx775289883** [pjialin/py12306#161]
![image](https://user-images.githubusercontent.com/46526084/56787390-fcc40580-682e-11e9-9cf8-8687670aa518.png)

**Comment by pjialin** [comment]
检查下 python 版本

**Comment by lx775289883** [comment]
Python版本对的啊，3.7.3，那个问题已经解决了，现在运行还是报错，不过跟之前不一样了





------------------ 原始邮件 ------------------
发件人: "pjialin"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 下午4:44
收件人: "pjialin/py12306"<py12306@noreply.github.com>;
抄送: "hj7"<775289883@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [pjialin/py12306] 运行报错 (#161)



检查下 python 版本

**Comment by pjialin** [comment]
具体什么错呢

**Comment by lx775289883** [comment]
请见附件




------------------ 原始邮件 ------------------
发件人: "pjialin"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 下午5:06
收件人: "pjialin/py12306"<py12306@noreply.github.com>;
抄送: "hj7"<775289883@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [pjialin/py12306] 运行报错 (#161)



具体什么错呢

**Comment by pjialin** [comment]
没有看到附件，直接贴错误日志在这里就行

**Comment by lx775289883** [comment]
好的
77528@DESKTOP-0L3G495 MINGW64 /e/Git/py12306 (master)
$ python main.py -t
######## py12306 ▒▒Ʊ▒▒▒֣▒▒▒▒▒▒▒Ϊ▒▒Դ▒▒▒ߣ▒▒▒▒▒▒▒▒▒▒▒ҵ▒▒; ########
▒▒ǰΪ▒▒▒▒ģʽ▒▒▒▒▒▒▒▒▒▒▒▒ɺ▒▒Զ▒▒▒▒▒
WEB ▒▒▒▒ҳ▒▒▒ѿ▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ַ + ▒˿▒ 8008 ▒▒▒в鿴
Traceback (most recent call last):
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 493, in connect
    sock = self._connect()
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 550, in _connect
    raise err
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 538, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] ▒▒▒▒Ŀ▒▒▒▒▒▒▒▒▒▒▒ܾ▒▒▒▒޷▒▒▒▒ӡ▒
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Program Files\Python37\lib\site-packages\redis\client.py", line 754, in execute_command
    connection.send_command(*args)
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 594, in send_packed_command
    self.connect()
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. ▒▒▒▒Ŀ▒▒▒▒▒▒▒▒▒▒▒ܾ▒▒▒▒޷▒▒▒▒ӡ▒.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 493, in connect
    sock = self._connect()
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 550, in _connect
    raise err
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 538, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] ▒▒▒▒Ŀ▒▒▒▒▒▒▒▒▒▒▒ܾ▒▒▒▒޷▒▒▒▒ӡ▒
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 15, in main
    App.run()
  File "E:\Git\py12306\py12306\app.py", line 38, in run
    self.start()
  File "E:\Git\py12306\py12306\app.py", line 41, in start
    Config().run()
  File "E:\Git\py12306\py12306\config.py", line 124, in run
    self.start()
  File "E:\Git\py12306\py12306\config.py", line 131, in start
    self.save_to_remote()
  File "E:\Git\py12306\py12306\config.py", line 150, in save_to_remote
    Cluster().session.set_pickle(Cluster().KEY_CONFIGS, self.envs)
  File "E:\Git\py12306\py12306\cluster\redis.py", line 51, in set_pickle
    return self.set(name, pickle.dumps(value, 0).decode())
  File "E:\Git\py12306\py12306\cluster\redis.py", line 37, in set
    return super().set(name, available_value(value), ex=ex, px=px, nx=nx, xx=xx)
  File "D:\Program Files\Python37\lib\site-packages\redis\client.py", line 1394, in set
    return self.execute_command('SET', *pieces)
  File "D:\Program Files\Python37\lib\site-packages\redis\client.py", line 760, in execute_command
    connection.send_command(*args)
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 594, in send_packed_command
    self.connect()
  File "D:\Program Files\Python37\lib\site-packages\redis\connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. ▒▒▒▒Ŀ▒▒▒▒▒▒▒▒▒▒▒ܾ▒▒▒▒޷▒▒▒▒ӡ▒.
77528@DESKTOP-0L3G495 MINGW64 /e/Git/py12306 (master)
$

------------------ 原始邮件 ------------------
发件人: "pjialin"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 下午5:18
收件人: "pjialin/py12306"<py12306@noreply.github.com>;
抄送: "hj7"<775289883@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [pjialin/py12306] 运行报错 (#161)



没有看到附件，直接贴错误日志在这里就行

**Comment by pjialin** [comment]
```
```

**Comment by lx775289883** [comment]
？？？？？







------------------ 原始邮件 ------------------
发件人: "pjialin"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 下午5:23
收件人: "pjialin/py12306"<py12306@noreply.github.com>;
抄送: "hj7"<775289883@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [pjialin/py12306] 运行报错 (#161)

**Comment by pjialin** [comment]
#62

**Comment by samwhf** [comment]
SyntaxError: invalid syntax 你的第一个问题怎么解决的，是哪里语法错误
