### ISSUE TITLE
测试不通过，编码问题

### ISSUE THREAD

**Issue by MatthewZou9419** [pjialin/py12306#162]
拉了最新代码，还是出现编码问题

Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 14, in main
    CommonLog.print_welcome()
  File "F:\py12306\py12306\log\common_log.py", line 79, in print_welcome
    if Config().WEB_ENABLE:
  File "F:\py12306\py12306\helpers\func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "F:\py12306\py12306\config.py", line 114, in __init__
    self.init_envs()
  File "F:\py12306\py12306\config.py", line 153, in init_envs
    self.envs = EnvLoader.load_with_file(self.CONFIG_FILE)
  File "F:\py12306\py12306\config.py", line 229, in load_with_file
    exec(content)
  File "<string>", line 1
    ﻿# -*- coding: utf-8 -*-
    ^
SyntaxError: invalid character in identifier

**Comment by pjialin** [comment]
看贴的代码是文件被修改过吧，正确头应该是这样的
```python
# -*- coding: utf-8 -*-
```
