### ISSUE TITLE
终端报错

### ISSUE THREAD

**Issue by chenfengfeng** [pjialin/py12306#165]
```python
######## py12306 购票助手，本程序为开源工具，请勿用于商业用途 ########

日志已输出到文件中: runtime/12306.log

WEB 管理页面已开启，请访问 主机地址 + 端口 8008 进行查看

 * Serving Flask app "py12306.web.web" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='api.ruokuai.com', port=80): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/chenzefeng/Documents/py12306/py12306/user/job.py", line 63, in run
    self.start()
  File "/Users/chenzefeng/Documents/py12306/py12306/user/job.py", line 76, in start
    self.check_heartbeat()
  File "/Users/chenzefeng/Documents/py12306/py12306/user/job.py", line 86, in check_heartbeat
    if not self.handle_login(): return
  File "/Users/chenzefeng/Documents/py12306/py12306/user/job.py", line 114, in handle_login
    return self.login()
  File "/Users/chenzefeng/Documents/py12306/py12306/user/job.py", line 127, in login
    answer = AuthCode.get_auth_code(self.session)
  File "/Users/chenzefeng/Documents/py12306/py12306/helpers/auth_code.py", line 31, in get_auth_code
    position = OCR.get_img_position(img)
  File "/Users/chenzefeng/Documents/py12306/py12306/helpers/OCR.py", line 30, in get_img_position
    return self.get_img_position_by_ruokuai(img)
  File "/Users/chenzefeng/Documents/py12306/py12306/helpers/OCR.py", line 37, in get_img_position_by_ruokuai
    result = rc.rk_create(img, 6113)
  File "/Users/chenzefeng/Documents/py12306/py12306/vender/ruokuai/main.py", line 35, in rk_create
    r = requests.post('http://api.ruokuai.com/create.json', data=params, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='api.ruokuai.com', port=80): Read timed out. (read timeout=20)
```

好像是验证码链接超时,然后就卡住了?

**Comment by pjialin** [comment]
是的，验证码超时了， 程序会自动重试的。

**Comment by chenfengfeng** [comment]
@pjialin 但是貌似会卡住,可用状态一直是失败,除非我把进程停止并且重新允许才可以

**Comment by pjialin** [comment]
@chenfengfeng 了解，回头看能不能复现

**Comment by pjialin** [comment]
已更换新的打码方式
