### ISSUE TITLE
提交订单报错

### ISSUE THREAD

**Issue by tokiii** [pjialin/py12306#180]
`Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 26, in main
    Query.run()
  File "/Users/lost/Documents/pyProject/py12306/py12306/query/query.py", line 54, in run
    self.start()
  File "/Users/lost/Documents/pyProject/py12306/py12306/query/query.py", line 78, in start
    jobs_do(self.jobs, 'run')
  File "/Users/lost/Documents/pyProject/py12306/py12306/helpers/func.py", line 146, in jobs_do
    getattr(job, do)()
  File "/Users/lost/Documents/pyProject/py12306/py12306/query/job.py", line 109, in run
    self.start()
  File "/Users/lost/Documents/pyProject/py12306/py12306/query/job.py", line 126, in start
    self.handle_response(response)
  File "/Users/lost/Documents/pyProject/py12306/py12306/query/job.py", line 178, in handle_response
    self.handle_seats(allow_seats, ticket_info)
  File "/Users/lost/Documents/pyProject/py12306/py12306/query/job.py", line 226, in handle_seats
    order_result = self.do_order(user)
  File "/Users/lost/Documents/pyProject/py12306/py12306/query/job.py", line 234, in do_order
    order = Order(user=user, query=self)
  File "/Users/lost/Documents/pyProject/py12306/py12306/order/order.py", line 45, in __init__
    self.make_passenger_ticket_str()
  File "/Users/lost/Documents/pyProject/py12306/py12306/order/order.py", line 441, in make_passenger_ticket_str
    enc_str=passenger['enc_str'],
KeyError: 'enc_str'`

**Comment by pjialin** [comment]
这个可能是之前已经保存过乘客信息了，就没有进行更新了，可以先在 `runtime` 目录里将账号对应的 `passenger` 文件手动删除下，试试，后面修复下这个问题

**Comment by pjialin** [comment]
已修复
