### ISSUE TITLE
order.py中enc_str 报错

### ISSUE THREAD

**Issue by Jnjie1895** [pjialin/py12306#182]
测试均通过了，且查询过程也正常，但是正常运行抢票时出错，具体步骤为乘客验证成功之后，会出现如下报错：
![error](https://user-images.githubusercontent.com/55220732/64760826-3d69b480-d56d-11e9-89f7-27d27de04d44.png)

**Comment by pjialin** [comment]
是否是最新的代码呢？

**Comment by Jnjie1895** [comment]
> 是否是最新的代码呢？

我今天直接用这个在windows下python的虚拟环境里面安装的，
git clone https://github.com/pjialin/py12306；顺便提一句，以上的过程我均在dos里面执行的命令，刚刚把文件放在pycharm里面执行后，出现的不同的反馈，如下：
Traceback (most recent call last):
  File "C:/Users/EDZ/py12306/main.py", line 4, in <module>
    from py12306.app import *
  File "C:\Users\EDZ\py12306\py12306\app.py", line 8, in <module>
    from py12306.helpers.notification import Notification
  File "C:\Users\EDZ\py12306\py12306\helpers\notification.py", line 5, in <module>
    from py12306.helpers.request import Request
  File "C:\Users\EDZ\py12306\py12306\helpers\request.py", line 5, in <module>
    from requests_html import HTMLSession, HTMLResponse
ModuleNotFoundError: No module named 'requests_html'

**Comment by pjialin** [comment]
今天有提交，更新下代码呢

**Comment by pjialin** [comment]
#183
