### ISSUE TITLE
项目启动报错，12306做了限制？没查到数据吗？

### ISSUE THREAD

**Issue by misikco** [pjialin/py12306#193]
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 20, in main
    Query.check_before_run()
  File "C:\Users\Administrator\Desktop\py12306-1.0.0\py12306\query\query.py", line 59, in check_before_run
    self = cls()
  File "C:\Users\Administrator\Desktop\py12306-1.0.0\py12306\helpers\func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "C:\Users\Administrator\Desktop\py12306-1.0.0\py12306\query\query.py", line 35, in __init__
    self.get_query_api_type()
  File "C:\Users\Administrator\Desktop\py12306-1.0.0\py12306\query\query.py", line 154, in get_query_api_type
    self.api_type = res.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by pjialin** [comment]
应该是网络的问题，重试下呢

**Comment by misikco** [comment]
改了下代码 跳过去这个正则查询 ，但是报302
