### ISSUE TITLE
登上去了，但是过一会就掉了，并且提示错误

### ISSUE THREAD

**Issue by LOST-Atlantis** [pjialin/py12306#210]
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 26, in main
    Query.run()
  File "D:\12306\12306\py12306-master\py12306\query\query.py", line 54, in run
    self.start()
  File "D:\12306\12306\py12306-master\py12306\query\query.py", line 78, in start
    jobs_do(self.jobs, 'run')
  File "D:\12306\12306\py12306-master\py12306\helpers\func.py", line 146, in jobs_do
    getattr(job, do)()
  File "D:\12306\12306\py12306-master\py12306\query\job.py", line 109, in run
    self.start()
  File "D:\12306\12306\py12306-master\py12306\query\job.py", line 126, in start
    self.handle_response(response)
  File "D:\12306\12306\py12306-master\py12306\query\job.py", line 166, in handle_response
    results = self.get_results(response)
  File "D:\12306\12306\py12306-master\py12306\query\job.py", line 249, in get_results
    result = response.json().get('data.result')
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by LOST-Atlantis** [comment]
国庆想回家，求助

**Comment by LOST-Atlantis** [comment]
关掉CDN

**Comment by EVINK** [comment]
502 是服务器链接的问题， 考虑到是12306 有可能是把你ban了
