### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by alterem** [pjialin/py12306#237]
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 20, in main
    Query.check_before_run()
  File "/Users/alterem/Documents/my-finishing/py12306/py12306/query/query.py", line 59, in check_before_run
    self = cls()
  File "/Users/alterem/Documents/my-finishing/py12306/py12306/helpers/func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "/Users/alterem/Documents/my-finishing/py12306/py12306/query/query.py", line 35, in __init__
    self.get_query_api_type()
  File "/Users/alterem/Documents/my-finishing/py12306/py12306/query/query.py", line 154, in get_query_api_type
    self.api_type = res.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by hsinyan7** [comment]
我也是，有时可以有时不可以，怀疑是编码问题

**Comment by yearning1103** [comment]
＋1

**Comment by Noboru-Chen** [comment]
+1

**Comment by TechnicolorTheClown** [comment]
+1
