### ISSUE TITLE
获取用户乘客列表失败，错误原因: [] 3 秒后重试

### ISSUE THREAD

**Issue by ljd321** [pjialin/py12306#239]
如题，测试的时候出现这个问题，请问有大佬知道怎么解决吗？

**Comment by pjialin** [comment]
检查下用户是否登录成功了，代码是否最新的。

**Comment by ljd321** [comment]
> 检查下用户是否登录成功了，代码是否最新的。

用户成功登录了，代码是最新的，环境是虚拟机ubuntu16.04TLS，python是3.8.0，用的是virtualenv+pyenv

**Comment by pjialin** [comment]
> > 检查下用户是否登录成功了，代码是否最新的。
> 
> 用户成功登录了，代码是最新的，环境是虚拟机ubuntu16.04TLS，python是3.8.0，用的是virtualenv+pyenv

登录成功那个地方能正确显示用户名吗
```
# 欢迎回来，xxx #
```

**Comment by ljd321** [comment]
> > > 检查下用户是否登录成功了，代码是否最新的。
> > 
> > 
> > 用户成功登录了，代码是最新的，环境是虚拟机ubuntu16.04TLS，python是3.8.0，用的是virtualenv+pyenv
> 
> 登录成功那个地方能正确显示用户名吗
> 
> ```
> # 欢迎回来，xxx #
> ```

可以

**Comment by pjialin** [comment]
看不出来什么问题，贴下日志吧

**Comment by ljd321** [comment]
> 看不出来什么问题，贴下日志吧
现在运行会出现以下错误，网上说加上encode("utf-8-sig")，但是不清楚要加在哪
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/ljd/.pyenv/versions/3.8.0/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ljd/.pyenv/versions/3.8.0/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ljd/py12306/py12306/user/job.py", line 63, in run
    self.start()
  File "/home/ljd/py12306/py12306/user/job.py", line 76, in start
    self.check_heartbeat()
  File "/home/ljd/py12306/py12306/user/job.py", line 86, in check_heartbeat
    if not self.handle_login(): return
  File "/home/ljd/py12306/py12306/user/job.py", line 114, in handle_login
    return self.login()
  File "/home/ljd/py12306/py12306/user/job.py", line 130, in login
    result = response.json()
  File "/home/ljd/.pyenv/versions/env380/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/ljd/.pyenv/versions/3.8.0/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/ljd/.pyenv/versions/3.8.0/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ljd/.pyenv/versions/3.8.0/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by pjialin** [comment]
没用 3.8 测试过，等有空测试下看下。

**Comment by qiuxiaojian** [comment]
我用3.8也出现了这个问题

**Comment by womesmile** [comment]
Python 3.6.3 同样出现了这个问题，-t 命令测试的时候 会出现， 获取用户乘客列表失败，错误原因: [] 3 秒后重试， 运行的时候会出现，打码失败: 错误原因 从免费打码获取结果失败  5 秒后重新获取验证码。 买的那一趟车明明有符合要求的票，就是一直在查询，没有看到进入购票的提示

**Comment by zhouwx19** [comment]
* Debug mode: off
用户状态已过期，正在重新登录
正在登录用户 
正在下载验证码...
验证码验证成功 开始登录...
# 欢迎回来，False #

早上用得好好的，已经下了一单了，不知道为什么变成这样了

**Comment by GentlemanSu** [comment]
请问这个问题解决了吗？我也遇到了这个问题
获取用户乘客列表失败，错误原因: [] 3 秒后重试

**Comment by ShengZhang2016** [comment]
刚刚在测试的时候也遇到了。

**Comment by ShengZhang2016** [comment]
log:
```查询任务 北京 -> 深圳 正在验证乘客信息
--------------------------------------------------
{
    "validateMessagesShowId": "_validatorMessage",
    "status": true,
    "httpstatus": 200,
    "data": {
        "isExist": false,
        "exMsg": "\u5f53\u524d\u65f6\u95f4\u4e0d\u53ef\u9884\u8ba2",
        "normal_passengers": null,
        "dj_passengers": null
    },
    "messages": [],
    "validateMessages": {}
}```
不知道为什么data里面normal_passengers 为什么是null， isExist 是false。
希望大佬能看到
