### ISSUE TITLE
测试失败'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by wxhzk** [pjialin/py12306#245]
多线程查询: 未开启
CDN 状态: 未开启
通知状态:		语音验证码: 已开启		
查询间隔: 1 秒
用户心跳检测间隔: 120 秒
WEB 管理页面: 已开启

Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 20, in main
    Query.check_before_run()
  File "/sourcecode/12306/py12306/py12306/query/query.py", line 59, in check_before_run
    self = cls()
  File "/sourcecode/12306/py12306/py12306/helpers/func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "/sourcecode/12306/py12306/py12306/query/query.py", line 35, in __init__
    self.get_query_api_type()
  File "/sourcecode/12306/py12306/py12306/query/query.py", line 154, in get_query_api_type
    self.api_type = res.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by yearning1103** [comment]
我也是一样的问题  有些头疼  不知道哪里出错了

**Comment by cloudswave** [comment]
删除缓存即可：git status查看生成的pyc文件，然后删除：
 rm -rf py12306/__init__.pyc
 rm -rf  py12306/helpers/__init__.pyc
 rm -rf  py12306/app.pyc
