### ISSUE TITLE
运行错误！

### ISSUE THREAD

**Issue by parzulpan** [pjialin/py12306#247]
Traceback (most recent call last):
  File "D:/job/projects/code/py12306/main.py", line 64, in <module>
    main()
  File "D:/job/projects/code/py12306/main.py", line 20, in main
    Query.check_before_run()
  File "D:\job\projects\code\py12306\py12306\query\query.py", line 59, in check_before_run
    self = cls()
  File "D:\job\projects\code\py12306\py12306\helpers\func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "D:\job\projects\code\py12306\py12306\query\query.py", line 35, in __init__
    self.get_query_api_type()
  File "D:\job\projects\code\py12306\py12306\query\query.py", line 154, in get_query_api_type
    self.api_type = res.group(1)
AttributeError: 'NoneType' object has no attribute 'group

**Comment by parzulpan** [comment]
有时可以运行，可能是编码问题。
若快打码已经挂了，能支持下其他的打码平台吗？

**Comment by pjialin** [comment]
这个问题重试下即可，后面会修复下

**Comment by pjialin** [comment]
打码问题已在上个 issue 中讨论

**Comment by out0fmemory** [comment]
+1，一直报这个错误，重试也不行

**Comment by jinyu121** [comment]
Docker里面同样遇到此问题。感觉应该先加一个是不是None的判断。

**Comment by 1619513467** [comment]
表示遇到同样的错误。不知道怎么修复

**Comment by 1619513467** [comment]
表示遇到同样的错误。不知道怎么修复

**Comment by 1619513467** [comment]
表示遇到同样的错误。不知道怎么修复

**Comment by 1619513467** [comment]
表示遇到同样的错误。不知道怎么修复

**Comment by 1619513467** [comment]
表示遇到同样的错误。不知道怎么修复

**Comment by 1619513467** [comment]
表示遇到同样的错误。不知道怎么修复
