### ISSUE TITLE
运行提示“KeyError: '深圳'”

### ISSUE THREAD

**Issue by baoroushi** [pjialin/py12306#258]
>> 第 4 次查询 深圳 -> 岳阳 2019-12-20 17:28:02
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 26, in main
    Query.run()
  File "/usr/local/scripts/12306/py12306/query/query.py", line 54, in run
    self.start()
  File "/usr/local/scripts/12306/py12306/query/query.py", line 78, in start
    jobs_do(self.jobs, 'run')
  File "/usr/local/scripts/12306/py12306/helpers/func.py", line 146, in jobs_do
    getattr(job, do)()
  File "/usr/local/scripts/12306/py12306/query/job.py", line 109, in run
    self.start()
  File "/usr/local/scripts/12306/py12306/query/job.py", line 122, in start
    self.refresh_station(station)
  File "/usr/local/scripts/12306/py12306/query/job.py", line 324, in refresh_station
    self.left_station_code = Station.get_station_key_by_name(self.left_station)
  File "/usr/local/scripts/12306/py12306/helpers/station.py", line 41, in get_station_key_by_name
    return self.station_kvs[name].decode()
KeyError: '深圳'

**Comment by baoroushi** [comment]
@classmethod
    def get_station_key_by_name(cls, name):
        self = cls()
        return self.station_kvs[name]
是返回的self.station_kvs[name]值类型问题吗？尝试改为拼音 shenzhen 也提示相同的ERROR

**Comment by pjialin** [comment]
我这测试没有问题的，确认下 `data/stations.txt` 是否丢失或者被修改，再试试
