### ISSUE TITLE
requests_html文件未找到

### ISSUE THREAD

**Issue by zsg0601** [pjialin/py12306#28]
root@Korea:/py12306# python main.py -t
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from py12306.app import *
  File "/py12306/py12306/app.py", line 7, in <module>
    from py12306.helpers.notification import Notification
  File "/py12306/py12306/helpers/notification.py", line 5, in <module>
    from py12306.helpers.request import Request
  File "/py12306/py12306/helpers/request.py", line 4, in <module>
    from requests_html import HTMLSession, HTMLResponse
ModuleNotFoundError: No module named 'requests_html'

**Comment by pjialin** [comment]
@zsg0601 检查 pip 关联的 python 是不是当前执行的 python。可以执行 `python -c 'import requests_html'` 进行确认

**Comment by zsg0601** [comment]
好像因为azure网络问题....
