### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by out0fmemory** [pjialin/py12306#283]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/py12306_1/py12306/py12306/query/job.py", line 314, in check_passengers
    passengers = User.get_passenger_for_members(self.members, self.account_key)
  File "/root/py12306_1/py12306/py12306/user/user.py", line 93, in get_passenger_for_members
    return user.get_passengers_by_members(members)
  File "/root/py12306_1/py12306/py12306/user/job.py", line 382, in get_passengers_by_members
    passenger['passenger_type'] = UserType.ADULT
TypeError: 'NoneType' object does not support item assignment

**Comment by out0fmemory** [comment]
已查明原因，乘车人配置错误，example里边的``*王五``没有删除导致的
