### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by xingheng** [pjialin/py12306#286]
```
➜  py12306 git:(master) ✗ python main.py
######## py12306 购票助手，本程序为开源工具，请勿用于商业用途 ########

日志已输出到文件中: runtime/12306.log

WEB 管理页面已开启，请访问 主机地址 + 端口 8008 进行查看

 * Serving Flask app "py12306.web.web" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-5, started daemon 123145551134720)>>
Traceback (most recent call last):
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/robot/Documents/Projects/gitRepository/py12306/py12306/user/job.py", line 63, in run
    self.start()
  File "/Users/robot/Documents/Projects/gitRepository/py12306/py12306/user/job.py", line 76, in start
    self.check_heartbeat()
  File "/Users/robot/Documents/Projects/gitRepository/py12306/py12306/user/job.py", line 86, in check_heartbeat
    if not self.handle_login(): return
  File "/Users/robot/Documents/Projects/gitRepository/py12306/py12306/user/job.py", line 114, in handle_login
    return self.login()
  File "/Users/robot/Documents/Projects/gitRepository/py12306/py12306/user/job.py", line 126, in login
    answer = AuthCode.get_auth_code(self.session)
  File "/Users/robot/Documents/Projects/gitRepository/py12306/py12306/helpers/auth_code.py", line 30, in get_auth_code
    img = self.download_code()
  File "/Users/robot/Documents/Projects/gitRepository/py12306/py12306/helpers/auth_code.py", line 61, in download_code
    return self.download_code()
  File "/Users/robot/Documents/Projects/gitRepository/py12306/py12306/helpers/auth_code.py", line 61, in download_code
    return self.download_code()
  File "/Users/robot/Documents/Projects/gitRepository/py12306/py12306/helpers/auth_code.py", line 61, in download_code
    return self.download_code()
  [Previous line repeated 953 more times]
  File "/Users/robot/Documents/Projects/gitRepository/py12306/py12306/helpers/auth_code.py", line 52, in download_code
    response = self.session.get(url)
  File "/Users/robot/.pyenv/versions/venv37/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Users/robot/Documents/Projects/gitRepository/py12306/py12306/helpers/request.py", line 60, in request
    response = super().request(*args, **kwargs)
  File "/Users/robot/.pyenv/versions/venv37/lib/python3.7/site-packages/requests_html.py", line 672, in request
    r = super(HTMLSession, self).request(*args, **kwargs)
  File "/Users/robot/.pyenv/versions/venv37/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/robot/.pyenv/versions/venv37/lib/python3.7/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/robot/.pyenv/versions/venv37/lib/python3.7/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/robot/.pyenv/versions/venv37/lib/python3.7/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/Users/robot/.pyenv/versions/venv37/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/robot/.pyenv/versions/venv37/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/robot/.pyenv/versions/venv37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/robot/.pyenv/versions/venv37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/robot/.pyenv/versions/venv37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/http/client.py", line 330, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/http/client.py", line 224, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/email/parser.py", line 68, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/email/parser.py", line 57, in parse
    feedparser.feed(data)
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/email/feedparser.py", line 176, in feed
    self._call_parse()
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/email/feedparser.py", line 180, in _call_parse
    self._parse()
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/email/feedparser.py", line 295, in _parsegen
    if self._cur.get_content_maintype() == 'message':
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/email/message.py", line 594, in get_content_maintype
    ctype = self.get_content_type()
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/email/message.py", line 578, in get_content_type
    value = self.get('content-type', missing)
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/email/message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/email/_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/email/_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/email/utils.py", line 57, in _has_surrogates
    s.encode()
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 936, in _bootstrap_inner
    (self.name, _format_exc()), file=_sys.stderr)
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/traceback.py", line 497, in __init__
    _seen=_seen)
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/traceback.py", line 497, in __init__
    _seen=_seen)
  File "/Users/robot/.pyenv/versions/3.7.4/lib/python3.7/traceback.py", line 497, in __init__
    _seen=_seen)
  [Previous line repeated 494 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by yasir-fareed-ahmed-grotabyte** [comment]
Getting the same error.
Were you able to find a solution? 
Thanks!
