### ISSUE TITLE
web 管理页面打不开是怎么解决哦

### ISSUE THREAD

**Issue by xinruoyusixian** [pjialin/py12306#290]
xception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\Desktop\8285\py12306-master\py12306-master\py12306\web\web.py", line 58, in run_session
    self.session.run(debug=debug, port=Config().WEB_PORT, host='0.0.0.0')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\cli.py", line 629, in show_server_banner
    click.echo(message)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\utils.py", line 218, in echo
    file = _default_text_stdout()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\_compat.py", line 675, in func
    rv = wrapper_func()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\_compat.py", line 436, in get_text_stdout
    rv = _get_windows_console_stream(sys.stdout, encoding, errors)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\_winconsole.py", line 295, in _get_windows_console_stream
    func = _stream_factories.get(f.fileno())

**Comment by windsorcerer** [comment]
防火墙关了没？端口设置了没？

**Comment by Hubupup** [comment]
我也遇到了这个情况，无法进入web管理页面。试过firefox和edge。
配置如下：
`# Web 管理
WEB_ENABLE = 1  # 是否打开 Web 管理
WEB_USER = {  # 登录信息
    'username': 'admin',
    'password': 'password'
}
WEB_PORT = 8008  # 监听端口`
