### ISSUE TITLE
UTF-8错误UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by Hubupup** [pjialin/py12306#296]
运行程序时报错(utf-8),打开log的情况下,运行报错;关闭log,会报相同错误,但可以运行,不过进不去web管理页面（不知道与此错误是否有关）。
报错内容如下：
<details>
<summary>Exception in thread Thread-10:</summary>

```python
    
Exception in thread Thread-10:

Traceback (most recent call last):
  File "C:\Users\星缘\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
 File "C:\Users\星缘\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Data\Study\python Study\project\12306\py12306\py12306\web\web.py", line 58, in run_session
    self.session.run(debug=debug, port=Config().WEB_PORT, host='0.0.0.0')
  File "C:\Users\星缘\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "C:\Users\星缘\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 1009, in run_simple
    inner()
  File "C:\Users\星缘\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 962, in inner
    fd=fd,
  File "C:\Users\星缘\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 805, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "C:\Users\星缘\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 698, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "C:\Users\星缘\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\星缘\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 139, in server_bind
    self.server_name = socket.getfqdn(host)
  File "C:\Users\星缘\AppData\Local\Programs\Python\Python37\lib\socket.py", line 676, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 0: invalid continuation byte

```
</details>
main.py首行编码内容如下：

`# -*- coding: utf-8 -*-`

**Comment by Foreen-EE** [comment]
我也有这样的问题
