### ISSUE TITLE
报的是NoneType,没有group的问题

### ISSUE THREAD

**Issue by fenglijunnb** [pjialin/py12306#351]
$ python main.py
######## py12306 购票助手，本程序为开源工具，请勿用于商业用途 ########

WEB 管理页面已开启，请访问 主机地址 + 端口 8008 进行查看

# 节点 master 已离开集群，当前节点列表 [  ] #
# 节点 master 成功加入到集群，当前节点列表 [ *master ] #
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 20, in main
    Query.check_before_run()
  File "D:\PYTHON\py12306\py12306\query\query.py", line 59, in check_before_run
    self = cls()
  File "D:\PYTHON\py12306\py12306\helpers\func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "D:\PYTHON\py12306\py12306\query\query.py", line 35, in __init__
    self.get_query_api_type()
  File "D:\PYTHON\py12306\py12306\query\query.py", line 154, in get_query_api_type
    self.api_type = res.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by okeeper** [comment]
我也遇到了，单节点启动报错
![image](https://user-images.githubusercontent.com/8952298/71810709-f79da280-30ad-11ea-966a-9f2e72878489.png)

**Comment by zwc456baby** [comment]
怀疑是ip被封之后才会出现的
我有一个 ip 被封了，12306.cn 上查不了车次了
爆出的错误和你的一样

然后我更换网络，再启动没有任何问题

注：同一台设备，同样的环境。仅仅更换 ip 而已，这个错误就消失了。

**Comment by Shawnqqq** [comment]
似乎是ip被封了，rm -rf ~/.ssh/known_hosts，尝试清空known_hosts的ip操作记录就可以了

**Comment by StudyingMan-JHY** [comment]
res = re.search(r'var CLeftTicketUrl = \'(leftTicket/queryG)\';', response.text)
