### ISSUE TITLE
py12306助手运行测试提示错误

### ISSUE THREAD

**Issue by githubsupvip** [pjialin/py12306#388]
验证码验证成功 开始登录...
>> 第 6 次查询 北京 -> 深圳 2020-08-28 09:24:35
乘车日期错误，比当前时间还早！！
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 26, in main
    Query.run()
  File "/py12306/py12306/query/query.py", line 54, in run
    self.start()
  File "/py12306/py12306/query/query.py", line 78, in start
    jobs_do(self.jobs, 'run')
  File "/py12306/py12306/helpers/func.py", line 146, in jobs_do
    getattr(job, do)()
  File "/py12306/py12306/query/job.py", line 112, in run
    self.start()
  File "/py12306/py12306/query/job.py", line 128, in start
    response = self.query_by_date(date)
  File "/py12306/py12306/query/job.py", line 164, in query_by_date
    self.judge_date_legal(date)
  File "/py12306/py12306/query/job.py", line 151, in judge_date_legal
    raise RuntimeError(msg)
RuntimeError: 乘车日期错误，比当前时间还早！！

**Comment by firekirin67** [comment]
注销掉配置文件env.py 120-160行的配置就行
