### ISSUE TITLE
py12306运行提示乘车日期错误，比当前时间还早！

### ISSUE THREAD

**Issue by githubsupvip** [pjialin/py12306#389]
验证码验证成功 开始登录...
>> 第 1 次查询 北京 -> 深圳 2020-08-28 11:38:06
乘车日期错误，比当前时间还早！！
Traceback (most recent call last):
  File "/Myproject/Py12306/main.py", line 64, in <module>
    main()
  File "/Myproject/Py12306/main.py", line 26, in main
    Query.run()
  File "/Myproject/Py12306/py12306/query/query.py", line 54, in run
    self.start()
  File "/Myproject/Py12306/py12306/query/query.py", line 78, in start
    jobs_do(self.jobs, 'run')
  File "/Myproject/Py12306/py12306/helpers/func.py", line 146, in jobs_do
    getattr(job, do)()
  File "/Myproject/Py12306/py12306/query/job.py", line 112, in run
    self.start()
  File "/Myproject/Py12306/py12306/query/job.py", line 128, in start
    response = self.query_by_date(date)
  File "/Myproject/Py12306/py12306/query/job.py", line 164, in query_by_date
    self.judge_date_legal(date)
  File "/Myproject/Py12306/py12306/query/job.py", line 151, in judge_date_legal
    raise RuntimeError(msg)
RuntimeError: 乘车日期错误，比当前时间还早！！

Process finished with exit code 1

**Comment by firekirin67** [comment]
注释掉配置文件env.py  120-160行的配置就行
