### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 18211167516** [pjialin/py12306#394]
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 20, in main
    Query.check_before_run()
  File "C:\Users\baibai\python\py12306\py12306\query\query.py", line 59, in check_before_run
    self = cls()
  File "C:\Users\baibai\python\py12306\py12306\helpers\func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "C:\Users\baibai\python\py12306\py12306\query\query.py", line 35, in __init__
    self.get_query_api_type()
  File "C:\Users\baibai\python\py12306\py12306\query\query.py", line 154, in get_query_api_type
    self.api_type = res.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by lhpmain** [comment]
不在维护了吗？

**Comment by NAMANANAS** [comment]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from py12306.app import *
  File "/Users/zcool/Documents/z_Tool/py12306/py12306/app.py", line 6, in <module>
    from py12306.helpers.func import *
  File "/Users/zcool/Documents/z_Tool/py12306/py12306/helpers/func.py", line 159
    def dict_count_key_num(data: dict, key, like=False):
                               ^
SyntaxError: invalid syntax

报错
