### ISSUE TITLE
抢票成功后程序报错 get_station_by(key, 'key') 返回 None

### ISSUE THREAD

**Issue by BerginJay** [pjialin/py12306#441]
日志显示下单成功，随后主程序报错如下
```shell
Traceback (most recent call last):  
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 26, in main
    Query.run()
  File "~/py12306/py12306/query/query.py", line 56, in run
    self.start()
  File "~/py12306/py12306/query/query.py", line 80, in start
    jobs_do(self.jobs, 'run')
  File "~/py12306/py12306/helpers/func.py", line 148, in jobs_do
    getattr(job, do)()
  File "~/py12306/py12306/query/job.py", line 111, in run
    self.start()
  File "~/py12306/py12306/query/job.py", line 128, in start
    self.handle_response(response)
  File "~/py12306/py12306/query/job.py", line 198, in handle_response
    self.handle_seats(allow_seats, ticket_info)
  File "~/py12306/py12306/query/job.py", line 246, in handle_seats
    order_result = self.do_order(user)
  File "~/py12306/py12306/query/job.py", line 255, in do_order
    return order.order()
  File "~/py12306/py12306/order/order.py", line 197, in order
    return self.normal_order()
  File "~/py12306/py12306/order/order.py", line 227, in normal_order
    self.order_did_success()
  File "~/py12306/py12306/order/order.py", line 235, in order_did_success
    self.send_notification()
  File "~/py12306/py12306/order/order.py", line 241, in send_notification
    info_message = OrderLog.get_order_success_notification_info(self.query_ins)
  File "~/py12306/py12306/log/order_log.py", line 66, in get_order_success_notification_info
    query.get_info_of_left_station(),
  File "~/py12306/py12306/query/job.py", line 361, in get_info_of_left_station
    return Station.get_station_name_by_key(self.ticket_info[self.INDEX_LEFT_STATION])
  File "~/py12306/py12306/helpers/station.py", line 45, in get_station_name_by_key
    return cls.get_station_by(key, 'key').get('name')
AttributeError: 'NoneType' object has no attribute 'get'
```
日志显示
```log
...
>> 第 17050 次查询 joba 2023-01-07 08:00:32
[ 查询到座位可用 出发时间 XXX 车次 XXX 座位类型 二等座 余票数量 有 ]
检查完成 开始提交订单 
提交订单成功
检查订单成功
获取排队信息成功，目前排队人数 0, 余票还剩余 448 张
# 提交订单成功！#
第 1 次排队，请耐心等待
第 2 次排队，请耐心等待
第 3 次排队，请耐心等待
第 4 次排队，请耐心等待
第 5 次排队，请耐心等待
第 6 次排队，请耐心等待
第 7 次排队，请耐心等待
第 8 次排队，请耐心等待
第 9 次排队，请耐心等待
第 10 次排队，请耐心等待
# 车票购买成功，订单号 XXXXXXX #
```
之后就没有更多日志了。

今天买了两张票，都出现这样的问题，导致成功下单后没有邮件等提醒

**Comment by IronXiao** [comment]
感觉是火车站列表的问题，目前维护的站名列表信息比较老。

**Comment by BerginJay** [comment]
@IronXiao 转到您的fork了，感谢！
