### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by Binary233** [pjialin/py12306#451]
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\asyncio\base_events.py", line 455, in run_until_complete
    self.run_forever()
  File "D:\Program Files\Python36\lib\asyncio\base_events.py", line 409, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
PS C:\Users\Shen\Desktop\py12306>

**Comment by IronXiao** [comment]
建议重启

**Comment by Binary233** [comment]
> 

重启试了，不行

**Comment by Binary233** [comment]
> 建议重启

重启试了，不行

**Comment by IronXiao** [comment]
估计是环境问题，建议可以用Anaconda 配一个新环境运行。我这边Python 3.8.10 运行的很丝滑。
