### ISSUE TITLE
使用自己制作的镜像运行出错

### ISSUE THREAD

**Issue by wzzYtu** [pjialin/py12306#453]
从git上拉下代码，然后使用`docker build -t py:v1 .`制作镜像，然后启动镜像报以下错误
Traceback (most recent call last):

  File "main.py", line 4, in <module>

    from py12306.app import *

  File "/code/py12306/app.py", line 7, in <module>

    from py12306.helpers.notification import Notification

  File "/code/py12306/helpers/notification.py", line 5, in <module>

    from py12306.helpers.request import Request

  File "/code/py12306/helpers/request.py", line 5, in <module>

    from requests_html import HTMLSession, HTMLResponse

  File "/usr/local/lib/python3.6/site-packages/requests_html.py", line 9, in <module>

    import pyppeteer

  File "/usr/local/lib/python3.6/site-packages/pyppeteer/__init__.py", line 40, in <module>

    from pyppeteer.launcher import connect, launch, executablePath  # noqa: E402

  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 26, in <module>

    from pyppeteer.browser import Browser

  File "/usr/local/lib/python3.6/site-packages/pyppeteer/browser.py", line 13, in <module>

    from pyppeteer.connection import Connection

  File "/usr/local/lib/python3.6/site-packages/pyppeteer/connection.py", line 13, in <module>

    from websockets.legacy.client import connect as ws_connect

ModuleNotFoundError: No module named 'websockets.legacy'

**Comment by gyr66** [comment]
我把基础镜像换成`FROM python:3.8`就不再有这个问题了
