### ISSUE TITLE
订单占位完成之后出现如下错误

### ISSUE THREAD

**Issue by black-zyp** [pjialin/py12306#459]
`Exception in thread Thread-13:
Traceback (most recent call last):
  File "/home/zyp/software/anaconda3/envs/12306_envs/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/zyp/software/anaconda3/envs/12306_envs/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zyp/program/12306/py12306-master/py12306/query/job.py", line 111, in run
    self.start()
  File "/home/zyp/program/12306/py12306-master/py12306/query/job.py", line 128, in start
    self.handle_response(response)
  File "/home/zyp/program/12306/py12306-master/py12306/query/job.py", line 198, in handle_response
    self.handle_seats(allow_seats, ticket_info)
  File "/home/zyp/program/12306/py12306-master/py12306/query/job.py", line 246, in handle_seats
    order_result = self.do_order(user)
  File "/home/zyp/program/12306/py12306-master/py12306/query/job.py", line 255, in do_order
    return order.order()
  File "/home/zyp/program/12306/py12306-master/py12306/order/order.py", line 197, in order
    return self.normal_order()
  File "/home/zyp/program/12306/py12306-master/py12306/order/order.py", line 227, in normal_order
    self.order_did_success()
  File "/home/zyp/program/12306/py12306-master/py12306/order/order.py", line 235, in order_did_success
    self.send_notification()
  File "/home/zyp/program/12306/py12306-master/py12306/order/order.py", line 241, in send_notification
    info_message = OrderLog.get_order_success_notification_info(self.query_ins)
  File "/home/zyp/program/12306/py12306-master/py12306/log/order_log.py", line 66, in get_order_success_notification_info
    query.get_info_of_left_station(),
  File "/home/zyp/program/12306/py12306-master/py12306/query/job.py", line 361, in get_info_of_left_station
    return Station.get_station_name_by_key(self.ticket_info[self.INDEX_LEFT_STATION])
  File "/home/zyp/program/12306/py12306-master/py12306/helpers/station.py", line 45, in get_station_name_by_key
    return cls.get_station_by(key, 'key').get('name')
AttributeError: 'NoneType' object has no attribute 'get'`

请问这是什么原因呀

**Comment by dfldylan** [comment]
station.txt里有你的车站吗？

**Comment by black-zyp** [comment]
station.txt这个文件在哪里 我没有找到，我只修改了env.py这个文件

**Comment by black-zyp** [comment]
哦 抱歉 我刚刚找到了 我看下

**Comment by black-zyp** [comment]
我确定station.txt中存在我的车站

**Comment by kosncn** [comment]
#506

**Comment by kosncn** [comment]
#506
更新了下车站信息文件
[stations.txt](https://github.com/pjialin/py12306/files/15158532/stations.txt)
