### ISSUE TITLE
cls.get_station_by(key, 'key')返回None

### ISSUE THREAD

**Issue by cynthia4869** [pjialin/py12306#497]
新建job含北京丰台站或者抢票成功后但是有北京丰台站时都会报这个错

File "~/py12306/py12306/query/job.py", line 361, in get_info_of_left_station
    return Station.get_station_name_by_key(self.ticket_info[self.INDEX_LEFT_STATION])
  File "~/py12306/py12306/helpers/station.py", line 45, in get_station_name_by_key
    return cls.get_station_by(key, 'key').get('name')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by cynthia4869** [comment]
>> 第 113072 次查询 哈尔滨 -> 北京 2024-02-06 12:45:59
[ 查询到座位可用 出发时间 20240219 车次 G910 座位类型 二等座 余票数量 11 ]
检查完成 开始提交订单 
提交订单成功
检查订单成功
获取排队信息成功，目前排队人数 0, 余票还剩余 11 张
# 提交订单成功！#
第 1 次排队，请耐心等待
第 2 次排队，请耐心等待
第 3 次排队，请耐心等待
第 4 次排队，请耐心等待
# 车票购买成功，订单号 EF16867967 #


Traceback (most recent call last):
  File ".\main.py", line 64, in <module>
    main()
  File ".\main.py", line 26, in main
    Query.run()
  File "D:\py12306\py12306\query\query.py", line 56, in run
    self.start()
  File "D:\py12306\py12306\query\query.py", line 80, in start
    jobs_do(self.jobs, 'run')
  File "D:\py12306\py12306\helpers\func.py", line 148, in jobs_do
    getattr(job, do)()
  File "D:\py12306\py12306\query\job.py", line 111, in run
    self.start()
  File "D:\py12306\py12306\query\job.py", line 128, in start
    self.handle_response(response)
  File "D:\py12306\py12306\query\job.py", line 198, in handle_response
    self.handle_seats(allow_seats, ticket_info)
  File "D:\py12306\py12306\query\job.py", line 246, in handle_seats
    order_result = self.do_order(user)
  File "D:\py12306\py12306\query\job.py", line 255, in do_order
    return order.order()
  File "D:\py12306\py12306\order\order.py", line 197, in order
    return self.normal_order()
  File "D:\py12306\py12306\order\order.py", line 227, in normal_order
    self.order_did_success()
  File "D:\py12306\py12306\order\order.py", line 235, in order_did_success
    self.send_notification()
  File "D:\py12306\py12306\order\order.py", line 241, in send_notification
    info_message = OrderLog.get_order_success_notification_info(self.query_ins)
  File "D:\py12306\py12306\log\order_log.py", line 68, in get_order_success_notification_info
    query.get_info_of_arrive_station(),
  File "D:\py12306\py12306\query\job.py", line 364, in get_info_of_arrive_station
    return Station.get_station_name_by_key(self.ticket_info[self.INDEX_ARRIVE_STATION])
  File "D:\py12306\py12306\helpers\station.py", line 45, in get_station_name_by_key
    return cls.get_station_by(key, 'key').get('name')
AttributeError: 'NoneType' object has no attribute 'get'

又出现了这个报错

**Comment by cynthia4869** [comment]
终于找到Config().STATION_FILE在哪了......
data/stations.txt 新增下None的车站 
e.g.2957@bjcy|北京朝阳|IFP|beijingchaoyang|bjcy
其中IFP是电报码 
http://cnrail.geogv.org/zhcn/station/630610
