### ISSUE TITLE
运行测试不通过

### ISSUE THREAD

**Issue by rollzhangus** [pjialin/py12306#57]
系统环境：Win10 专业版 64位 17134
Python版本：3.6.8

```
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 13, in main
    CommonLog.print_welcome()
  File "G:\App\py12306\py12306\log\common_log.py", line 69, in print_welcome
    if Config().WEB_ENABLE:
  File "G:\App\py12306\py12306\helpers\func.py", line 29, in singleton_new
    it.__init_original__(*args, **kw)
  File "G:\App\py12306\py12306\config.py", line 98, in __init__
    self.init_envs()
  File "G:\App\py12306\py12306\config.py", line 137, in init_envs
    self.envs = EnvLoader.load_with_file(self.CONFIG_FILE)
  File "G:\App\py12306\py12306\config.py", line 213, in load_with_file
    exec(content)
  File "<string>", line 1
    ﻿# encoding=utf8
    ^
SyntaxError: invalid character in identifier
```

**Comment by pjialin** [comment]
那个是编码问题，已提交一个版本修复了，拉下最新代码就好了

#14

**Comment by MatthewZou9419** [comment]
拉了最新代码，还是报错
`Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 14, in main
    CommonLog.print_welcome()
  File "F:\py12306-1.0.0\py12306\log\common_log.py", line 79, in print_welcome
    if Config().WEB_ENABLE:
  File "F:\py12306-1.0.0\py12306\helpers\func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "F:\py12306-1.0.0\py12306\config.py", line 114, in __init__
    self.init_envs()
  File "F:\py12306-1.0.0\py12306\config.py", line 153, in init_envs
    self.envs = EnvLoader.load_with_file(self.CONFIG_FILE)
  File "F:\py12306-1.0.0\py12306\config.py", line 229, in load_with_file
    exec(content)
  File "<string>", line 1
    ﻿# -*- coding: utf-8 -*-
    ^
SyntaxError: invalid character in identifier`

**Comment by MatthewZou9419** [comment]
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 14, in main
    CommonLog.print_welcome()
  File "F:\py12306-1.0.0\py12306\log\common_log.py", line 79, in print_welcome
    if Config().WEB_ENABLE:
  File "F:\py12306-1.0.0\py12306\helpers\func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "F:\py12306-1.0.0\py12306\config.py", line 114, in __init__
    self.init_envs()
  File "F:\py12306-1.0.0\py12306\config.py", line 153, in init_envs
    self.envs = EnvLoader.load_with_file(self.CONFIG_FILE)
  File "F:\py12306-1.0.0\py12306\config.py", line 229, in load_with_file
    exec(content)
  File "<string>", line 1
    ﻿# -*- coding: utf-8 -*-
    ^
SyntaxError: invalid character in identifier

**Comment by MatthewZou9419** [comment]
拉了最新代码，还是报错
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 14, in main
    CommonLog.print_welcome()
  File "F:\py12306-1.0.0\py12306\log\common_log.py", line 79, in print_welcome
    if Config().WEB_ENABLE:
  File "F:\py12306-1.0.0\py12306\helpers\func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "F:\py12306-1.0.0\py12306\config.py", line 114, in __init__
    self.init_envs()
  File "F:\py12306-1.0.0\py12306\config.py", line 153, in init_envs
    self.envs = EnvLoader.load_with_file(self.CONFIG_FILE)
  File "F:\py12306-1.0.0\py12306\config.py", line 229, in load_with_file
    exec(content)
  File "<string>", line 1
    ﻿# -*- coding: utf-8 -*-
    ^
SyntaxError: invalid character in identifier
