### ISSUE TITLE
运行不通过

### ISSUE THREAD

**Issue by wolframwj** [pjialin/py12306#58]
日志如下：
(base) C:\Users\chd\Desktop\py12306>python main.py
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 13, in main
    CommonLog.print_welcome()
  File "C:\Users\chd\Desktop\py12306\py12306\log\common_log.py", line 66, in print_welcome
    if not Const.IS_TEST and Config().OUT_PUT_LOG_TO_FILE_ENABLED:
  File "C:\Users\chd\Desktop\py12306\py12306\helpers\func.py", line 29, in singleton_new
    it.__init_original__(*args, **kw)
  File "C:\Users\chd\Desktop\py12306\py12306\config.py", line 98, in __init__
    self.init_envs()
  File "C:\Users\chd\Desktop\py12306\py12306\config.py", line 137, in init_envs
    self.envs = EnvLoader.load_with_file(self.CONFIG_FILE)
  File "C:\Users\chd\Desktop\py12306\py12306\config.py", line 213, in load_with_file
    exec(content)
  File "<string>", line 1
    ﻿# encoding=utf-8

**Comment by pjialin** [comment]
更新下代码
#57
