### ISSUE TITLE
ssh 连接服务器执行 python main.py 出错

### ISSUE THREAD

**Issue by ShenDada** [pjialin/py12306#59]
root@vultr:~/12306/py12306# python main.py -t
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from py12306.app import *
  File "/root/12306/py12306/py12306/app.py", line 29
SyntaxError: Non-ASCII character '\xe7' in file /root/12306/py12306/py12306/app.py on line 30, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by ShenDada** [comment]
添加了 #coding=utf-8
最后出现下面错误
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from py12306.app import *
  File "/root/12306/py12306/py12306/app.py", line 7, in <module>
    from py12306.helpers.func import *
  File "/root/12306/py12306/py12306/helpers/func.py", line 154
    def dict_count_key_num(data: dict, key, like=False):
                               ^
SyntaxError: invalid syntax

在不同机器登陆ssh 后出现的问题

**Comment by pjialin** [comment]
查看 #56
