### ISSUE TITLE
分布式问题

### ISSUE THREAD

**Issue by MartinWong-H** [pjialin/py12306#62]

**Comment by MartinWong-H** [comment]
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 493, in connect
    sock = self._connect()
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 550, in _connect
    raise err
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 538, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/client.py", line 754, in execute_command
    connection.send_command(*args)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 493, in connect
    sock = self._connect()
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 550, in _connect
    raise err
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 538, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 14, in main
    App.run()
  File "/Users/Martin_Huang/Desktop/py12306-master/py12306/app.py", line 37, in run
    self.start()
  File "/Users/Martin_Huang/Desktop/py12306-master/py12306/app.py", line 40, in start
    Config().run()
  File "/Users/Martin_Huang/Desktop/py12306-master/py12306/config.py", line 108, in run
    self.start()
  File "/Users/Martin_Huang/Desktop/py12306-master/py12306/config.py", line 115, in start
    self.save_to_remote()
  File "/Users/Martin_Huang/Desktop/py12306-master/py12306/config.py", line 134, in save_to_remote
    Cluster().session.set_pickle(Cluster().KEY_CONFIGS, self.envs)
  File "/Users/Martin_Huang/Desktop/py12306-master/py12306/cluster/redis.py", line 51, in set_pickle
    return self.set(name, pickle.dumps(value, 0).decode())
  File "/Users/Martin_Huang/Desktop/py12306-master/py12306/cluster/redis.py", line 37, in set
    return super().set(name, available_value(value), ex=ex, px=px, nx=nx, xx=xx)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/client.py", line 1394, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/client.py", line 760, in execute_command
    connection.send_command(*args)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused

**Comment by MartinWong-H** [comment]
hello  想开启分布式时， 运行的时候报错了，这个能怎么解吗

**Comment by pjialin** [comment]
redis 连接失败，检查 redis 配置

**Comment by MartinWong-H** [comment]
好的咧，老哥想问问后面看能不能更新一版，班次时间区间处理的。不然想要去头去尾的班次，还要抓它接口数据提班次再转数组。有些麻烦 特别是50 60个班次的。

**Comment by pjialin** [comment]
嗯，可以加个设置排除的班次

**Comment by pjialin** [comment]
@MartinWong-H  新提交已加上
